#!/usr/bin/env python3
"""Embed only the three named, local console assets. No network/build framework."""
import pathlib
import sys
root = pathlib.Path(__file__).resolve().parent.parent
out = pathlib.Path(sys.argv[1])
chunks = ['/* Generated by tools/embed-web.py; edit web/ instead. */\n']
for name, file in [('index', 'index.html'), ('app', 'app.js'), ('style', 'style.css')]:
    data = (root / 'web' / file).read_bytes()
    if not data or len(data) > 1024 * 1024:
        raise SystemExit(f'invalid embedded asset size: {file}')
    chunks.append(f'static const unsigned char wadb_web_{name}[] = {{\n')
    chunks.extend(','.join(str(b) for b in data[i:i+24]) + ',\n' for i in range(0, len(data), 24))
    chunks.append('};\n')
out.parent.mkdir(parents=True, exist_ok=True)
out.write_text(''.join(chunks))
